// In this file you can specify the trial data for your experiment

var order_1 = _.shuffle(['study_images/Decoy11.png', 'study_images/Decoy12.png', 'study_images/Lure1.png', 'study_images/Truth1.png'])
var order_2 = _.shuffle(['study_images/Decoy21.png', 'study_images/Decoy22.png', 'study_images/Lure2.png', 'study_images/Truth2.png'])
var order_3 = _.shuffle(['study_images/Decoy31.png', 'study_images/Decoy32.png', 'study_images/Lure3.png', 'study_images/Truth3.png'])
var order_4 = _.shuffle(['study_images/Decoy41.png', 'study_images/Decoy42.png', 'study_images/Lure4.png', 'study_images/Truth4.png'])
var order_5 = _.shuffle(['study_images/Decoy51.png', 'study_images/Decoy52.png', 'study_images/Lure5.png', 'study_images/Truth5.png'])
var order_6 = _.shuffle(['study_images/Decoy61.png', 'study_images/Decoy62.png', 'study_images/Lure6.png', 'study_images/Truth6.png'])

const image_selection_practice = {
    practice_teammate: [
        {
            condition: "teammate",
            question: "Choose a map.",
            evidence: "This is the current Evidence:",
            evidencepic: 'study_images/Helpful3.png',
            picture1: order_3[0],
            picture2: order_3[1],
            picture3: order_3[2],
            picture4: order_3[3],
            option1: 'order_3[0]',
            option2: 'order_3[1]',
            option3: 'order_3[2]',
            option4: 'order_3[3]',
        },
        {
            condition: "teammate",
            question: "Choose a map.",
            evidence: "This is the current Evidence:",
            evidencepic: 'study_images/Misleading4_0.png',
            picture1: order_4[0],
            picture2: order_4[1],
            picture3: order_4[2],
            picture4: order_4[3],
            option1: 'order_4[0]',
            option2: 'order_4[1]',
            option3: 'order_4[2]',
            option4: 'order_4[3]',
        },
        {
            condition: "teammate",
            question: "Choose a map.",
            evidence: "This is the current Evidence:",
            evidencepic: 'study_images/Uninformative5.png',
            picture1: order_5[0],
            picture2: order_5[1],
            picture3: order_5[2],
            picture4: order_5[3],
            option1: 'order_5[0]',
            option2: 'order_5[1]',
            option3: 'order_5[2]',
            option4: 'order_5[3]',
        },
        {
            condition: "teammate",
            question: "Choose a map.",
            evidence: "This is the current Evidence:",
            evidencepic: 'study_images/Helpful3.png',
            picture1: order_3[0],
            picture2: order_3[1],
            picture3: order_3[2],
            picture4: order_3[3],
            option1: 'order_3[0]',
            option2: 'order_3[1]',
            option3: 'order_3[2]',
            option4: 'order_3[3]',
        },

    ],

    practice_opponent: [
        {
            condition: "opponent",
            question: "Choose a map.",
            evidence: "This is the current Evidence:",
            evidencepic: 'study_images/Helpful1.png',
            picture1: order_1[0],
            picture2: order_1[1],
            picture3: order_1[2],
            picture4: order_1[3],
            option1: 'order_1[0]',
            option2: 'order_1[1]',
            option3: 'order_1[2]',
            option4: 'order_1[3]',
        },
        {
            condition: "opponent",
            question: "Choose a map.",
            evidence: "This is the current Evidence:",
            evidencepic: 'study_images/Misleading2_25.png',
            picture1: order_2[0],
            picture2: order_2[1],
            picture3: order_2[2],
            picture4: order_2[3],
            option1: 'order_2[0]',
            option2: 'order_2[1]',
            option3: 'order_2[2]',
            option4: 'order_2[3]',
        },
        {
            condition: "opponent",
            question: "Choose a map.",
            evidence: "This is the current Evidence:",
            evidencepic: 'study_images/Uninformative4.png',
            picture1: order_4[0],
            picture2: order_4[1],
            picture3: order_4[2],
            picture4: order_4[3],
            option1: 'order_4[0]',
            option2: 'order_4[1]',
            option3: 'order_4[2]',
            option4: 'order_4[3]',
        },
        {
            condition: "opponent",
            question: "Choose a map.",
            evidence: "This is the current Evidence:",
            evidencepic: 'study_images/Uninformative6.png',
            picture1: order_6[0],
            picture2: order_6[1],
            picture3: order_6[2],
            picture4: order_6[3],
            option1: 'order_6[0]',
            option2: 'order_6[1]',
            option3: 'order_6[2]',
            option4: 'order_6[3]',
        },
    ],
};

const image_selection_trials = {
    image_selection_teammate: [
        {
            condition: "teammate",
            question: "Choose a map.",
            evidence: "This is the current Evidence:",
            evidencepic: 'study_images/Helpful1.png',
            picture1: order_1[0],
            picture2: order_1[1],
            picture3: order_1[2],
            picture4: order_1[3],
            option1: 'order_1[0]',
            option2: 'order_1[1]',
            option3: 'order_1[2]',
            option4: 'order_1[3]',
        },
        {
            condition: "teammate",
            question: "Choose a map.",
            evidence: "This is the current Evidence:",
            evidencepic: 'study_images/Misleading1_50.png',
            picture1: order_1[0],
            picture2: order_1[1],
            picture3: order_1[2],
            picture4: order_1[3],
            option1: 'order_1[0]',
            option2: 'order_1[1]',
            option3: 'order_1[2]',
            option4: 'order_1[3]',
        },
        {
            condition: "teammate",
            question: "Choose a map.",
            evidence: "This is the current Evidence:",
            evidencepic: 'study_images/Uninformative1.png',
            picture1: order_1[0],
            picture2: order_1[1],
            picture3: order_1[2],
            picture4: order_1[3],
            option1: 'order_1[0]',
            option2: 'order_1[1]',
            option3: 'order_1[2]',
            option4: 'order_1[3]',
        },
        {
            condition: "teammate",
            question: "Choose a map.",
            evidence: "This is the current Evidence:",
            evidencepic: 'study_images/Helpful2.png',
            picture1: order_2[0],
            picture2: order_2[1],
            picture3: order_2[2],
            picture4: order_2[3],
            option1: 'order_2[0]',
            option2: 'order_2[1]',
            option3: 'order_2[2]',
            option4: 'order_2[3]',
        },
        {
            condition: "teammate",
            question: "Choose a map.",
            evidence: "This is the current Evidence:",
            evidencepic: 'study_images/Misleading2_25.png',
            picture1: order_2[0],
            picture2: order_2[1],
            picture3: order_2[2],
            picture4: order_2[3],
            option1: 'order_2[0]',
            option2: 'order_2[1]',
            option3: 'order_2[2]',
            option4: 'order_2[3]',
        },
        {
            condition: "teammate",
            question: "Choose a map.",
            evidence: "This is the current Evidence:",
            evidencepic: 'study_images/Uninformative2.png',
            picture1: order_2[0],
            picture2: order_2[1],
            picture3: order_2[2],
            picture4: order_2[3],
            option1: 'order_2[0]',
            option2: 'order_2[1]',
            option3: 'order_2[2]',
            option4: 'order_2[3]',
        },
        {
            condition: "teammate",
            question: "Choose a map.",
            evidence: "This is the current Evidence:",
            evidencepic: 'study_images/Helpful3.png',
            picture1: order_3[0],
            picture2: order_3[1],
            picture3: order_3[2],
            picture4: order_3[3],
            option1: 'order_3[0]',
            option2: 'order_3[1]',
            option3: 'order_3[2]',
            option4: 'order_3[3]',
        },
        {
            condition: "teammate",
            question: "Choose a map.",
            evidence: "This is the current Evidence:",
            evidencepic: 'study_images/Misleading3_25.png',
            picture1: order_3[0],
            picture2: order_3[1],
            picture3: order_3[2],
            picture4: order_3[3],
            option1: 'order_3[0]',
            option2: 'order_3[1]',
            option3: 'order_3[2]',
            option4: 'order_3[3]',
        },
        {
            condition: "teammate",
            question: "Choose a map.",
            evidence: "This is the current Evidence:",
            evidencepic: 'study_images/Uninformative3.png',
            picture1: order_3[0],
            picture2: order_3[1],
            picture3: order_3[2],
            picture4: order_3[3],
            option1: 'order_3[0]',
            option2: 'order_3[1]',
            option3: 'order_3[2]',
            option4: 'order_3[3]',
        },
        {
            condition: "teammate",
            question: "Choose a map.",
            evidence: "This is the current Evidence:",
            evidencepic: 'study_images/Helpful4.png',
            picture1: order_4[0],
            picture2: order_4[1],
            picture3: order_4[2],
            picture4: order_4[3],
            option1: 'order_4[0]',
            option2: 'order_4[1]',
            option3: 'order_4[2]',
            option4: 'order_4[3]',
        },
        {
            condition: "teammate",
            question: "Choose a map.",
            evidence: "This is the current Evidence:",
            evidencepic: 'study_images/Misleading4_0.png',
            picture1: order_4[0],
            picture2: order_4[1],
            picture3: order_4[2],
            picture4: order_4[3],
            option1: 'order_4[0]',
            option2: 'order_4[1]',
            option3: 'order_4[2]',
            option4: 'order_4[3]',
        },
        {
            condition: "teammate",
            question: "Choose a map.",
            evidence: "This is the current Evidence:",
            evidencepic: 'study_images/Uninformative4.png',
            picture1: order_4[0],
            picture2: order_4[1],
            picture3: order_4[2],
            picture4: order_4[3],
            option1: 'order_4[0]',
            option2: 'order_4[1]',
            option3: 'order_4[2]',
            option4: 'order_4[3]',
        },
        {
            condition: "teammate",
            question: "Choose a map.",
            evidence: "This is the current Evidence:",
            evidencepic: 'study_images/Helpful5.png',
            picture1: order_5[0],
            picture2: order_5[1],
            picture3: order_5[2],
            picture4: order_5[3],
            option1: 'order_5[0]',
            option2: 'order_5[1]',
            option3: 'order_5[2]',
            option4: 'order_5[3]',
        },
        {
            condition: "teammate",
            question: "Choose a map.",
            evidence: "This is the current Evidence:",
            evidencepic: 'study_images/Misleading5_50.png',
            picture1: order_5[0],
            picture2: order_5[1],
            picture3: order_5[2],
            picture4: order_5[3],
            option1: 'order_5[0]',
            option2: 'order_5[1]',
            option3: 'order_5[2]',
            option4: 'order_5[3]',
        },
        {
            condition: "teammate",
            question: "Choose a map.",
            evidence: "This is the current Evidence:",
            evidencepic: 'study_images/Uninformative5.png',
            picture1: order_5[0],
            picture2: order_5[1],
            picture3: order_5[2],
            picture4: order_5[3],
            option1: 'order_5[0]',
            option2: 'order_5[1]',
            option3: 'order_5[2]',
            option4: 'order_5[3]',
        },
        {
            condition: "teammate",
            question: "Choose a map.",
            evidence: "This is the current Evidence:",
            evidencepic: 'study_images/Helpful6.png',
            picture1: order_6[0],
            picture2: order_6[1],
            picture3: order_6[2],
            picture4: order_6[3],
            option1: 'order_6[0]',
            option2: 'order_6[1]',
            option3: 'order_6[2]',
            option4: 'order_6[3]',
        },
        {
            condition: "teammate",
            question: "Choose a map.",
            evidence: "This is the current Evidence:",
            evidencepic: 'study_images/Misleading6_0.png',
            picture1: order_6[0],
            picture2: order_6[1],
            picture3: order_6[2],
            picture4: order_6[3],
            option1: 'order_6[0]',
            option2: 'order_6[1]',
            option3: 'order_6[2]',
            option4: 'order_6[3]',
        },
        {
            condition: "teammate",
            question: "Choose a map.",
            evidence: "This is the current Evidence:",
            evidencepic: 'study_images/Uninformative6.png',
            picture1: order_6[0],
            picture2: order_6[1],
            picture3: order_6[2],
            picture4: order_6[3],
            option1: 'order_6[0]',
            option2: 'order_6[1]',
            option3: 'order_6[2]',
            option4: 'order_6[3]',
        },
    ],

    image_selection_opponent: [
        {
            condition: "opponent",
            question: "Choose a map.",
            evidence: "This is the current Evidence:",
            evidencepic: 'study_images/Helpful1.png',
            picture1: order_1[0],
            picture2: order_1[1],
            picture3: order_1[2],
            picture4: order_1[3],
            option1: 'order_1[0]',
            option2: 'order_1[1]',
            option3: 'order_1[2]',
            option4: 'order_1[3]',
        },
        {
            condition: "opponent",
            question: "Choose a map.",
            evidence: "This is the current Evidence:",
            evidencepic: 'study_images/Misleading1_50.png',
            picture1: order_1[0],
            picture2: order_1[1],
            picture3: order_1[2],
            picture4: order_1[3],
            option1: 'order_1[0]',
            option2: 'order_1[1]',
            option3: 'order_1[2]',
            option4: 'order_1[3]',
        },
        {
            condition: "opponent",
            question: "Choose a map.",
            evidence: "This is the current Evidence:",
            evidencepic: 'study_images/Uninformative1.png',
            picture1: order_1[0],
            picture2: order_1[1],
            picture3: order_1[2],
            picture4: order_1[3],
            option1: 'order_1[0]',
            option2: 'order_1[1]',
            option3: 'order_1[2]',
            option4: 'order_1[3]',
        },
        {
            condition: "opponent",
            question: "Choose a map.",
            evidence: "This is the current Evidence:",
            evidencepic: 'study_images/Helpful2.png',
            picture1: order_2[0],
            picture2: order_2[1],
            picture3: order_2[2],
            picture4: order_2[3],
            option1: 'order_2[0]',
            option2: 'order_2[1]',
            option3: 'order_2[2]',
            option4: 'order_2[3]',
        },
        {
            condition: "opponent",
            question: "Choose a map.",
            evidence: "This is the current Evidence:",
            evidencepic: 'study_images/Misleading2_25.png',
            picture1: order_2[0],
            picture2: order_2[1],
            picture3: order_2[2],
            picture4: order_2[3],
            option1: 'order_2[0]',
            option2: 'order_2[1]',
            option3: 'order_2[2]',
            option4: 'order_2[3]',
        },
        {
            condition: "opponent",
            question: "Choose a map.",
            evidence: "This is the current Evidence:",
            evidencepic: 'study_images/Uninformative2.png',
            picture1: order_2[0],
            picture2: order_2[1],
            picture3: order_2[2],
            picture4: order_2[3],
            option1: 'order_2[0]',
            option2: 'order_2[1]',
            option3: 'order_2[2]',
            option4: 'order_2[3]',
        },
        {
            condition: "opponent",
            question: "Choose a map.",
            evidence: "This is the current Evidence:",
            evidencepic: 'study_images/Helpful3.png',
            picture1: order_3[0],
            picture2: order_3[1],
            picture3: order_3[2],
            picture4: order_3[3],
            option1: 'order_3[0]',
            option2: 'order_3[1]',
            option3: 'order_3[2]',
            option4: 'order_3[3]',
        },
        {
            condition: "opponent",
            question: "Choose a map.",
            evidence: "This is the current Evidence:",
            evidencepic: 'study_images/Misleading3_25.png',
            picture1: order_3[0],
            picture2: order_3[1],
            picture3: order_3[2],
            picture4: order_3[3],
            option1: 'order_3[0]',
            option2: 'order_3[1]',
            option3: 'order_3[2]',
            option4: 'order_3[3]',
        },
        {
            condition: "opponent",
            question: "Choose a map.",
            evidence: "This is the current Evidence:",
            evidencepic: 'study_images/Uninformative3.png',
            picture1: order_3[0],
            picture2: order_3[1],
            picture3: order_3[2],
            picture4: order_3[3],
            option1: 'order_3[0]',
            option2: 'order_3[1]',
            option3: 'order_3[2]',
            option4: 'order_3[3]',
        },
        {
            condition: "opponent",
            question: "Choose a map.",
            evidence: "This is the current Evidence:",
            evidencepic: 'study_images/Helpful4.png',
            picture1: order_4[0],
            picture2: order_4[1],
            picture3: order_4[2],
            picture4: order_4[3],
            option1: 'order_4[0]',
            option2: 'order_4[1]',
            option3: 'order_4[2]',
            option4: 'order_4[3]',
        },
        {
            condition: "opponent",
            question: "Choose a map.",
            evidence: "This is the current Evidence:",
            evidencepic: 'study_images/Misleading4_0.png',
            picture1: order_4[0],
            picture2: order_4[1],
            picture3: order_4[2],
            picture4: order_4[3],
            option1: 'order_4[0]',
            option2: 'order_4[1]',
            option3: 'order_4[2]',
            option4: 'order_4[3]',
        },
        {
            condition: "opponent",
            question: "Choose a map.",
            evidence: "This is the current Evidence:",
            evidencepic: 'study_images/Uninformative4.png',
            picture1: order_4[0],
            picture2: order_4[1],
            picture3: order_4[2],
            picture4: order_4[3],
            option1: 'order_4[0]',
            option2: 'order_4[1]',
            option3: 'order_4[2]',
            option4: 'order_4[3]',
        },
        {
            condition: "opponent",
            question: "Choose a map.",
            evidence: "This is the current Evidence:",
            evidencepic: 'study_images/Helpful5.png',
            picture1: order_5[0],
            picture2: order_5[1],
            picture3: order_5[2],
            picture4: order_5[3],
            option1: 'order_5[0]',
            option2: 'order_5[1]',
            option3: 'order_5[2]',
            option4: 'order_5[3]',
        },
        {
            condition: "opponent",
            question: "Choose a map.",
            evidence: "This is the current Evidence:",
            evidencepic: 'study_images/Misleading5_50.png',
            picture1: order_5[0],
            picture2: order_5[1],
            picture3: order_5[2],
            picture4: order_5[3],
            option1: 'order_5[0]',
            option2: 'order_5[1]',
            option3: 'order_5[2]',
            option4: 'order_5[3]',
        },
        {
            condition: "opponent",
            question: "Choose a map.",
            evidence: "This is the current Evidence:",
            evidencepic: 'study_images/Uninformative5.png',
            picture1: order_5[0],
            picture2: order_5[1],
            picture3: order_5[2],
            picture4: order_5[3],
            option1: 'order_5[0]',
            option2: 'order_5[1]',
            option3: 'order_5[2]',
            option4: 'order_5[3]',
        },
        {
            condition: "opponent",
            question: "Choose a map.",
            evidence: "This is the current Evidence:",
            evidencepic: 'study_images/Helpful6.png',
            picture1: order_6[0],
            picture2: order_6[1],
            picture3: order_6[2],
            picture4: order_6[3],
            option1: 'order_6[0]',
            option2: 'order_6[1]',
            option3: 'order_6[2]',
            option4: 'order_6[3]',
        },
        {
            condition: "opponent",
            question: "Choose a map.",
            evidence: "This is the current Evidence:",
            evidencepic: 'study_images/Misleading6_0.png',
            picture1: order_6[0],
            picture2: order_6[1],
            picture3: order_6[2],
            picture4: order_6[3],
            option1: 'order_6[0]',
            option2: 'order_6[1]',
            option3: 'order_6[2]',
            option4: 'order_6[3]',
        },
        {
            condition: "opponent",
            question: "Choose a map.",
            evidence: "This is the current Evidence:",
            evidencepic: 'study_images/Uninformative6.png',
            picture1: order_6[0],
            picture2: order_6[1],
            picture3: order_6[2],
            picture4: order_6[3],
            option1: 'order_6[0]',
            option2: 'order_6[1]',
            option3: 'order_6[2]',
            option4: 'order_6[3]',
        },
    ]
};
