---
title: "Final take-home exam"
date: 'Due: Wednesday, February 10 by 08:00 pm CET'
author: ""
output: 
html_document:
toc: true
toc_depth: 2
highlight: tango
---
  

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE, error = F, message = F, warning = F)

```

```{r libraries, include=FALSE, message=FALSE, warning=FALSE}

# package for convenience functions (e.g. ggplot2, dplyr, etc.)
library(tidyverse)

# package for this course
library(aida)

# package for Bayesian regression
library(brms)                                         # Install readr package
 
library(dplyr)                                                  # Load dplyr package
library(plyr)                                                   # Load plyr package
library(readr) 

# parallel execution of Stan code
options(mc.cores = parallel::detectCores())

# use the aida-theme for plotting
theme_set(theme_aida())

# global color scheme / non-optimized
project_colors = c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "#000000")

# setting theme colors globally
scale_colour_discrete <- function(...) {
  scale_colour_manual(..., values = project_colors)
}
scale_fill_discrete <- function(...) {
  scale_fill_manual(..., values = project_colors)
} 

# nicer global knitr options
knitr::opts_chunk$set(warning = FALSE, message = FALSE, 
                      cache = TRUE, fig.align = 'center')
```


```{r}

d <- read.csv('resultsmerge.csv')
d
#we filter the data (age) important data, meaning the main trials, condition, trial_number, evidencepic, response


d_tidy <- d %>%
  group_by(age) %>%
  group_by(condition) %>%
  filter(trial_name != 'teammate_block_practice' & trial_name != 'opponent_block_practice') %>%
  select(response, condition, option1, picture1, option2, picture2, option3, picture3, option4, picture4, age, evidencepic)
d_tidy

d_tidy2 <- d_tidy %>%
      mutate(
        evidence = case_when(
          evidencepic %in% str_c("study_images/Helpful", 1:6, ".png") ~ "Helpful",
          evidencepic %in% str_c("study_images/Uninformative", 1:6, ".png") ~ "Uninformative",
          evidencepic %in% str_c("study_images/Misleading", 1:6, "_0.png") ~ "Misleading",
          evidencepic %in% str_c("study_images/Misleading", 1:6, "_50.png") ~ "Misleading",
          evidencepic %in% str_c("study_images/Misleading", 1:6, "_25.png") ~ "Misleading"
          ),
        response = case_when(
          response %in% str_c("order_", 1:6, "[", 0, "]") ~ "1",
          response %in% str_c("order_", 1:6, "[", 1, "]") ~ "2",
          response %in% str_c("order_", 1:6, "[", 2, "]") ~ "3",
          response %in% str_c("order_", 1:6, "[", 3, "]") ~ "4",
          response %in% str_c("order_", 1:6, "[", 4, "]") ~ "5",
          response %in% str_c("order_", 1:6, "[", 5, "]") ~ "6",
    )
  )
d_tidy2




t <- d_tidy2 %>%
  select(age, response, evidence, condition, picture1, picture2, picture3, picture4) %>%
t

t%>%
  group_by(condition) %>%
  group_by(picture1)%>%
  ggplot(aes(x = evidence))+
  geom_bar()
  
  mutate(
    Choice = case_when(
      response == 1 
    )
  )


```


```{r}
tidy%>%
  group_by(condition)


```
